### ISSUE TITLE
Error: Failed to initialize the Noble object: poweredOff

### ISSUE THREAD

**Issue by anoopmk007** [futomi/node-beacon-scanner#1]
When we are running  below code...

_const BeaconScanner = require('node-beacon-scanner');
const scanner = new BeaconScanner();

// Set an Event handler for becons
scanner.onadvertisement = (ad) => {
  console.log(JSON.stringify(ad, null, '  '));
};

// Start scanning
scanner.startScan().then(() => {
  console.log('Started to scan.')  ;
}).catch((error) => {
  console.error(error);
});_

getting below error

_Error: Failed to initialize the Noble object: poweredOff
    at Noble.noble.once (/Users/abc/node_modules/node-beacon-scanner/lib/scanner.js:98:16)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Noble.emit (events.js:211:7)
    at Noble.onStateChange (/Users/abc/node_modules/noble/lib/noble.js:85:8)
    at emitOne (events.js:116:13)
    at NobleBindings.emit (events.js:211:7)
    at NobleBindings.<anonymous> (/Users/abc/node_modules/noble/lib/mac/yosemite.js:78:8)
    at emitOne (events.js:116:13)
    at NobleBindings.emit (events.js:211:7)_

**Comment by anoopmk007** [comment]
bluetooth was off, after bluetooth turned on issue resolved

**Comment by futomi** [comment]
Never mind. Thank you for your feedback.
